### ISSUE TITLE
Pre release 4.2.0 error

### ISSUE THREAD

**Issue by thiagogebrimm** [aromaa/WorldGuardExtraFlagsPlugin#214]
```
[18:28:28 ERROR]: Could not pass event PlayerChangedWorldEvent to WorldGuardExtraFlags v4.2.0-SNAPSHOT
java.lang.NullPointerException: Cannot invoke "com.sk89q.worldguard.session.SessionManager.get(com.sk89q.worldguard.LocalPlayer)" because "this.sessionManager" is null
        at net.goldtreeservers.worldguardextraflags.listeners.EssentialsListener.onPlayerChangedWorldEvent(EssentialsListener.java:63) ~[WorldGuardExtraFlags.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor874.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1613]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.respawn(PlayerList.java:996) ~[purpur-1.18.2.jar:git-Purpur-1613]
        at net.minecraft.server.players.PlayerList.respawn(PlayerList.java:829) ~[purpur-1.18.2.jar:git-Purpur-1613]
        at org.bukkit.craftbukkit.v1_18_R2.entity.CraftPlayer.teleport(CraftPlayer.java:1194) ~[purpur-1.18.2.jar:git-Purpur-1613]
        at org.bukkit.craftbukkit.v1_18_R2.entity.CraftEntity.teleport(CraftEntity.java:563) ~[purpur-1.18.2.jar:git-Purpur-1613]
        at me.soekd.soduels.model.Game$join$2.invokeSuspend(隹踪錦工末閑:1580) ~[SODuels-1.0.0-SNAPSHOT.jar:?]
        at me.soekd.soduels.kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[SODuels-1.0.0-SNAPSHOT.jar:?]
        at me.soekd.soduels.kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[SODuels-1.0.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1613]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.2.jar:git-Purpur-1613]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1558) ~[purpur-1.18.2.jar:git-Purpur-1613]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1613]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1482) ~[purpur-1.18.2.jar:git-Purpur-1613]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.18.2.jar:git-Purpur-1613]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1613]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by aromaa** [comment]
I decided to just drop Essentials as dependency, what it was used for was pretty meaningless in general and could be achieved in other ways if really needed.
